version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aLkokdelfnvKKsasd33io
    restart: always
  web:
    build: .
    image: django_planetly
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aLkokdelfnvKKsasd33io
    depends_on:
      - migration
      - db
    restart: always
  create_usage_types:
    image: django_planetly
    command: python manage.py create_entries
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aLkokdelfnvKKsasd33io
    depends_on:
      - db
      - migration
    restart: on-failure
  migration:
    image: django_planetly
    command: python manage.py migrate
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aLkokdelfnvKKsasd33io
    depends_on:
      - db
    restart: on-failure